#!/bin/bash

if [ -z $1 ]; then
    echo "branchname?"
    exit
fi


git rev-parse 2> /dev/null
if [ $? -gt 0 ]; then
    echo "Not in a git repo!"
    exit
fi

git symbolic-ref HEAD refs/heads/$1
rm .git/index
git clean -fdx
git commit --allow-empty -m "Start $1 branch"
