#!/bin/bash

DEBUG=1
QUIET="--quiet"

function debug {
    if [ $DEBUG == 1 ]; then
        echo "DEBUG: $1"
    fi
}

function usage {
    echo "Usage: "
    exit
}

function set_action {
    if [ $ACTION != 0 ]; then
        debug "Errm ACTION is already set to ${ACTION}"
        echo "Only one function is possible at a time"
        usage
    else
        ACTION=$1
    fi
}


git rev-parse 2> /dev/null
if [ $? -gt 0 ]; then
    echo "Not in a git repo!"
    exit 128
fi

CWD=`pwd`
BASEDIR=`git basedir`

cd ${BASEDIR}

git dirtybranch
if [ $? == 1 ]; then
    debug "Current branch is dirty, stashing commits"
    git stash ${QUIET}
fi

ACTION=0

while test $# != 0
do
    case $1 in
    add)
        set_action ADD
        ;;

    list)
        set_action LIST
        ;;
    esac
    shift
done

debug "ACTION = $ACTION"

if [ $ACTION == 0 ]; then
    echo "I have nothing to do!"
    git stash pop ${QUIET}
    exit 1
fi

CURRENT_BRANCH=`git whichbranch`

if [ "`git findabranch todo`" == "todo" ]; then
    debug "We have a branch todo"
    git checkout ${QUIET} todo
else
    debug "There is no branch todo, lets create one"
    git emptybranch todo
fi

if [ $ACTION == "ADD" ]; then
    read -p "Please enter your new TODO: " TODO
    if [ -z "$TODO" ]; then
        debug "TODO is zero length!"
        git checkout ${QUIET} ${CURRENT_BRANCH}
        git stash pop ${QUIET}
        echo "TODO was empty!"
        exit
    fi
    debug "TODO is $TODO"
    echo "$TODO" >> todo
    echo "All done!"
fi

if [ $ACTION == "LIST" ]; then
    _IFS=${IFS}
    IFS=$'\n'
    for line in `cat todo`; do
        echo "* $line"
    done
    IFS=${_IFS}
fi

git dirtybranch
if [ $? == 1 ]; then
    # commit to todo
    git add -A
    git commit -m"todo checkin" ${QUIET}
fi


# Restore to previous point
git checkout ${CURRENT_BRANCH}
git stash pop
#git clean -fdx

cd ${CWD}
